### ISSUE TITLE
The version is not compatible with this julia version.

### ISSUE THREAD

**Issue by draftman9** [fannheyward/coc-julia#341] opened 2022-08-20 07:30 UTC
os: win10
editor: gvim 8.2

Here is the programming going wrong. 
![image](https://user-images.githubusercontent.com/99490289/185734217-d2b198e5-19c1-45e9-911b-7285ca5da5ab.png)

**Comment by lassepe** [comment] 2022-08-30 12:57
@fannheyward do you recall which Julia version you used to generate the Manifest.toml? It may be worth mentioning that version somewhere in the readme and advise users to point their `julia.executablePath` to a suitable binary. Alternatively, it may be worth even just downloading the correct version for this plugin via something like [juliaup](https://github.com/JuliaLang/juliaup).

**Comment by fannheyward** [comment] 2022-08-30 13:00
> which Julia version you used to generate the Manifest.toml

It should be 1.7.0, I didn't remember it correctly.

**Comment by lassepe** [comment] 2022-08-30 13:04
It may be worth running `Pkg.upgrade_manifest()` in `JuliaLS` and `compile_env` then. This way, the julia version will be stored inside the Manifest.toml and users may get a more informative error message.

**Comment by lassepe** [comment] 2022-08-30 13:39
This is a duplicate of #306. As pointed out there, the easiest way to fix this is by pointing `julia.executablePath` to a  Julia 1.7 binary.

**Closed** 2022-09-02 08:16 UTC
