### ISSUE TITLE
Language server crashed upon launch

### ISSUE THREAD

**Issue by tpoisot** [fannheyward/coc-julia#234] opened 2021-07-19 18:15 UTC
(using latest versions of everything)

It looks like coc-julia does not recognize the packages anymore - this is true of packages from stdlib *and* from packages installed in Project.toml

**Comment by lassepe** [comment] 2021-07-19 18:38
Which Julia version are you using?

**Comment by tpoisot** [comment] 2021-07-19 21:40
~~~
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4* (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 7
~~~

**Comment by tpoisot** [comment] 2021-07-19 21:41
Here's the nvim version as well

~~~
nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
~~~

**Comment by tpoisot** [comment] 2021-07-19 21:41
And some packages info

~~~
  [98e50ef6] JuliaFormatter v0.15.1
  [2b0e0bc5] LanguageServer v4.0.0
  [b3cc710f] StaticLint v8.0.0
  [cf896787] SymbolServer v7.0.0
~~~

**Comment by tpoisot** [comment] 2021-07-21 15:31
So, after enabling debugging, and starting from an empty project, I got this error (lightly edited and indented for clarity):

~~~
[Trace - 11:24:11 AM] Received notification 'telemetry/event'.
Params: {
    name: LSSymbolServerFailure,
    stacktrace: "",
    message: "
        ERROR: LoadError: MethodError: no method matching frommanifest(::Pkg.Types.Manifest, ::Base.UUID)
        Closest candidates are:
            frommanifest(!Matched::Pkg.Types.Context, ::Any) at ~/.julia/packages/SymbolServer/mibRY/src/utils.jl:128
            frommanifest(!Matched::Dict{Base.UUID, Pkg.Types.PackageEntry}, ::Any) at ~/.julia/packages/SymbolServer/mibRY/src/utils.jl:129
        Stacktrace:
        [1] top-level scope
            @ ~/.julia/packages/SymbolServer/mibRY/src/server.jl:61
            in expression starting at ~/.julia/packages/SymbolServer/mibRY/src/server.jl:1
    ",
    "command": "symserv_crash"
}
~~~

This seems to suggest that the server is fully crashed (and indeed, I'm unable to complete anything).

**Comment by tpoisot** [comment] 2021-07-21 15:37
Just to make sure that I hadn't changed anything by mistake, I wiped by `~/.julia` folder and the `coc-julia` and `coc-julia-data` folders. When I re-installed `coc-julia`, opening a Julia file gave this error (in nvim, not in the language server trace):

~~~
[coc.nvim] Error on activate extension coc-julia: Command failed: /usr/bin/julia --project=/home/tpoisot/.config/coc/extensions/node_modules/coc-julia/server/compile_env --startup-file=no --history-file=no -e "import PackageCom
piler; println(PackageCompiler.default_sysimg_path())"
ERROR: ArgumentError: Package PackageCompiler [9b87118b-4619-50d2-8e1e-99f35a4d4d9d] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
~~~

**Comment by tpoisot** [comment] 2021-07-21 15:42
So I went and instantiated the `~/.config/coc/...` folder, and re-stared nvim on a julia file, which led to this new error:

![2021-07-21-114122_1262x99_scrot](https://user-images.githubusercontent.com/579329/126517965-f4a00c26-01a6-4745-9088-7746531b0c67.png)

Running `CocList services` gives `julia [startFailed] julia, juliamarkdown`

**Comment by lassepe** [comment] 2021-07-21 15:44
Did you instantiate both `~/.config/coc/extensions/node_modules/coc-julia/server/{JuliaLS,compile_env}`?

**Comment by tpoisot** [comment] 2021-07-21 15:46
Yes to both now, and I'm still having the same issue:

![2021-07-21-114703_793x593_scrot](https://user-images.githubusercontent.com/579329/126518836-3db5532d-828d-4773-aa44-abc25bb4f138.png)

`CocInfo` indicates no issue with the julia service.

**Comment by tpoisot** [comment] 2021-07-21 15:48
looking at the language server trace, there's still the same issue: `frommanifest` has no matching method.

**Comment by kerkmann** [comment] 2021-07-21 17:36
Confirm.. After downgrade julia to 1.6.1 it's working. :)

**Comment by tpoisot** [comment] 2021-07-21 21:17
So I'm noticing that the `Manifest.toml` files are present in `coc-julia`, which shouldn't be the case?

**Comment by tpoisot** [comment] 2021-07-21 21:18
In addition, I'm unable to make the `julia.CompileLanguageServerBin` and `julia.CompileLanguageServerSysImage` commands work - the later complains about dependencies, the former about 

~~~
[ Info: Building a binary app for package '/home/tpoisot/.config/coc/extensions/node_modules/coc-julia/server/Ju
liaLS' to '/home/tpoisot/.config/coc/extensions/coc-julia-data/JuliaLS'.
ERROR: LoadError: IOError: open("/usr/lib/cups/backend/cups-brf", 0, 0): permission denied (EACCES)
Stacktrace:
 [1] bundle_julia_libraries(app_dir::String)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/EuZ2W/src/PackageCompiler.jl:741
 [2] create_app(package_dir::String, app_dir::String; app_name::Nothing, precompile_execution_file::Vector{Strin
g}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, audit::Bool, force::Boo
l, c_driver_program::String, cpu_target::String)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/EuZ2W/src/PackageCompiler.jl:665
 [3] compile_app(args::Vector{String})
   @ Main ~/.config/coc/extensions/node_modules/coc-julia/server/compile_env/compile.jl:44
 [4] main(args::Vector{String})
   @ Main ~/.config/coc/extensions/node_modules/coc-julia/server/compile_env/compile.jl:54
 [5] top-level scope
   @ ~/.config/coc/extensions/node_modules/coc-julia/server/compile_env/compile.jl:62
in expression starting at /home/tpoisot/.config/coc/extensions/node_modules/coc-julia/server/compile_env/compile
.jl:61
~~~

This sounds like issues with 1.6.2, so I'll get back to 1.6.1 for the moment

**Comment by lassepe** [comment] 2021-07-22 07:53
> So I'm noticing that the `Manifest.toml` files are present in `coc-julia`, which shouldn't be the case?

I think this is on purpose. The idea seems to be that `coc-julia` tries to record an exact state of packages that work together. That of course stops working once the versions recorded in the `Manifest.toml` have been resolved with a different Julia version. I thus end up calling `]up` in `~/.config/coc/extensions/node_modules/coc-julia/server/{compile_env,JuliaLS}` from time to time to get an updated language server. Personally, I would probably prefer if the environments therein only had a `Project.toml` with corresponding `[compat]` bounds but there may be a good reason why that was not done, @fannheyward ?

**Comment by fannheyward** [comment] 2021-07-22 08:37
@lassepe maybe it's better to keep `Project.toml` only, but the problem is, this need coc-julia users to do update time to time to keep it updated.

For most language server, for example what I did in coc-pyright/coc-rust-analyzer, the extension follows the LS  and lock to a _almost up to date_ version, users don't need to worry about the LS issue, just install the extension to use.For

For Julia LS, coc-julia follows how vscode-julia does, https://github.com/julia-vscode/julia-vscode/tree/master/scripts/environments/languageserver, but we don't have a high update frequency as vscode-julia did. This will make the LS failed in some cases.

**Comment by tpoisot** [comment] 2021-07-22 12:17
what about a `julia.UpdateDependecies` command or something similar?

**Comment by lassepe** [comment] 2021-08-10 21:10
@fannheyward does coc-julia currently ever update re-instantiate the environment in `~/.config/coc/extensions/node_modules/coc-julia/server/JuliaLS`? In particular, if one uses a system-image then it seems that any change of the `JuliaLS` manifest does not take any effect until the system-image is recompiled (which would have to happen manually I suppose?)

**Closed** 2021-08-13 03:59 UTC
Labels: help wanted

**Comment by fannheyward** [comment] 2021-08-13 06:48
@lassepe 

> any change of the JuliaLS manifest does not take any effect until the system-image is recompiled

Yes, you need to recompile manually.

**Comment by fannheyward** [comment] 2021-08-13 07:06
> Just to make sure that I hadn't changed anything by mistake, I wiped by `~/.julia` folder and the `coc-julia` and `coc-julia-data` folders. When I re-installed `coc-julia`, opening a Julia file gave this error (in nvim, not in the language server trace):
> 
> ```
> [coc.nvim] Error on activate extension coc-julia: Command failed: /usr/bin/julia --project=/home/tpoisot/.config/coc/extensions/node_modules/coc-julia/server/compile_env --startup-file=no --history-file=no -e "import PackageCom
> piler; println(PackageCompiler.default_sysimg_path())"
> ERROR: ArgumentError: Package PackageCompiler [9b87118b-4619-50d2-8e1e-99f35a4d4d9d] is required but does not seem to be installed:
>  - Run `Pkg.instantiate()` to install all recorded dependencies.
> ```

@tpoisot try v0.10.0 with Julia 1.6.2
