### ISSUE TITLE
`julia.CompileLanguageServerSysimg` shows confusing error message

### ISSUE THREAD

**Issue by lassepe** [fannheyward/coc-julia#184] opened 2021-05-11 11:18 UTC
When running `julia.CompileLanguageServerSysimg`, I get the following error message while running `compile_env/compile.jl`:

```
9 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
```

This error seems harmless in practice. At least the system image generated seems to work. However, the error message is a bit confusing and may point to the fact that there is something wrong with the way the project environment is set up.

**Comment by wangl-cc** [comment] 2021-05-12 06:54
I have tested and got a similar error. This error seems to caused by execute `runtests.jl` during compiling.

**Comment by fannheyward** [comment] 2021-05-12 06:55
https://github.com/fannheyward/coc-julia/commit/0bcb405ca4efd3844d172a5516765422d0bbc84d has removed `runtests.jl`.

**Comment by lassepe** [comment] 2021-05-12 07:04
@fannheyward I noticed that you removed the `runtests.jl` from the pre-compilation. While system-image precompilation is much quicker now, the system image that is generated does not seem pre-compile the commands. It seems to me that load-time is reduced (because `using LanguageServer` etc will be instant) but triggering some event (such as "jump to definition") has more lag then it used to have because these instructions are not actually pre-comiled.

Is this impression correct? If so, it may be better to still include `runtests.jl` for precompilation and file an issue with LanguageServer.jl for the errors in their tests.

**Comment by wangl-cc** [comment] 2021-05-12 07:39
I think this error is not caused by `runtests.jl` but `PackageCompiler.jl` v1.24 and `julia` v1.6,  see [this commit](https://github.com/JuliaLang/PackageCompiler.jl/commit/fec20d410220310a80edeea66e25936de3a624d9). Compilation with `PackageCompiler.jl` v1.25 works for me.

**Comment by fannheyward** [comment] 2021-05-13 03:42
Should be fixed with latest PackageCompiler and LanguageServer.jl:

```
❯ /Users/fannheyward/bin/julia --project="/Users/fannheyward/src/coc-julia/server/JuliaLS" --startup-file=no --history-file=no -e "using Pkg; Pkg.instantiate(
)"
  Installing known registries into `~/.julia`
registry `General` already exist in `~/.julia/registries/General`.
     Cloning git-repo `https://github.com/julia-vscode/LanguageServer.jl.git`
   Installed URIParser ────── v0.4.1
   Installed DocumentFormat ─ v3.2.3
   Installed JSONRPC ──────── v1.3.1
   Installed JSON ─────────── v0.21.1
   Installed StaticLint ───── v7.0.0
   Installed Tokenize ─────── v0.5.16
   Installed Parsers ──────── v1.1.0
   Installed SymbolServer ─── v6.0.1
   Installed CSTParser ────── v3.2.1
   Installed FilePathsBase ── v0.9.10
Precompiling project...
  12 dependencies successfully precompiled in 11 seconds (3 already precompiled)
```

Try v0.8.5.

**Closed by fannheyward** 2021-05-13 03:42 UTC
