### ISSUE TITLE
Broken autocompletion

### ISSUE THREAD

**Issue by JinraeKim** [fannheyward/coc-julia#194] opened 2021-05-26 00:36 UTC
I don't know since when the autocompletion began to be broken.

When I type some words to see the autocompletion list, it looks like:
![image](https://user-images.githubusercontent.com/43136096/119585416-9fcc1c80-be05-11eb-8347-c2ed443ada1c.png)

However, when I press `ctrl+p` to make it autocompleted, it becomes broken like:
![image](https://user-images.githubusercontent.com/43136096/119585431-a6f32a80-be05-11eb-9d93-143965a602b8.png)

I'm not sure that it's a problem of coc-julia.

Note: the broken word is quite random. For example,
![image](https://user-images.githubusercontent.com/43136096/119585568-e6ba1200-be05-11eb-8eb6-00b92b72d86b.png)

**Comment by fannheyward** [comment] 2021-05-26 01:12
Try to map your `<cr>` to do completion:

```
inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm()
      \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

**Comment by JinraeKim** [comment] 2021-05-26 01:30
@fannheyward In `.vimrc`?

Unfortunately, it doesn't work...
![image](https://user-images.githubusercontent.com/43136096/119589194-47991880-be0d-11eb-8ade-cb90d719bdb4.png)

**Comment by fannheyward** [comment] 2021-05-26 01:40
<img width="416" alt="截屏2021-05-26 上午9 39 00" src="https://user-images.githubusercontent.com/345274/119589826-3567ac00-be06-11eb-92a7-c0b9f359fdd3.png">

Can't reproduce, try to upgrade your LanguageServer.jl https://github.com/fannheyward/coc-julia/issues/163

**Comment by JinraeKim** [comment] 2021-05-26 01:57
@fannheyward Should LanguageServer.jl be installed on the base environment?
Is the following correct?:
Install LanguageServer.jl on the base environment and then `:CocCommand julia.CompileLanguageServerSysimg` if necessary.

**Comment by fannheyward** [comment] 2021-05-26 01:59
coc-julia has bundled the LanguageServer.jl, just run `:CocCommand julia.CompileLanguageServerSysimg`.

**Comment by JinraeKim** [comment] 2021-05-26 02:07
don't know why but cannot fix it...
Do you have an idea for an alternative way?
Can I reinstall all of `coc.nvim` and `coc-julia`? If so, can you share how to do it?

**Comment by JinraeKim** [comment] 2021-05-26 02:16
Note that this phenomenon occurs since `Julia Language Server Indexing packages...` appears.
![image](https://user-images.githubusercontent.com/43136096/119592556-acf00800-be13-11eb-8a8b-87b31f793916.png)

**Comment by fannheyward** [comment] 2021-05-26 02:32
Make sure you're using the latest coc-julia, 0.8.6, this has bundled the LanguageServer.jl that works.

`:CocCommand julia.CompileLanguageServerSysimg` maybe take 5 mins, please wait to finish.

**Comment by JinraeKim** [comment] 2021-05-26 02:48
I reinstalled `coc.nvim` and `coc-julia`, so I think that they may be the latest ones.
How to check the version of `coc-julia`?

+) Yes, I waited for the installation till it's completed.

**Comment by fannheyward** [comment] 2021-05-26 02:56
Install coc-julia by `:CocInstall coc-julia`

**Comment by JinraeKim** [comment] 2021-05-26 04:16
```
Install finished

- ✓ coc-julia Installed extension coc-julia@0.8.6 at /Users/jinrae/.config/coc/extensions/node_modules/coc-julia
```
but it still be broken.

**Comment by fannheyward** [comment] 2021-05-28 05:13
Try coc-julia v0.9.0 with LanguageServer.jl 4.0.

**Comment by JinraeKim** [comment] 2021-05-28 05:42
```
Install finished

- ✓ coc-julia Installed extension coc-julia@0.9.0 at /Users/jinrae/.config/coc/extensions/node_modules/coc-julia
```
![image](https://user-images.githubusercontent.com/43136096/119935619-be2b4700-bfc2-11eb-9de4-31022b65d4f1.png)

**Comment by JinraeKim** [comment] 2021-05-28 05:44
> Try coc-julia v0.9.0 with LanguageServer.jl 4.0.

Is there anything that I can help you?

**Comment by fannheyward** [comment] 2021-05-28 06:00
@JinraeKim can you post a mini jl file to reproduce this issue?

**Comment by JinraeKim** [comment] 2021-05-28 06:04
```julia
function sample_x()
end

function main()
    sa_x  # tried to autocomplete the word `sample_x` from `samp`
end
```
![image](https://user-images.githubusercontent.com/43136096/119937528-e2d4ee00-bfc5-11eb-9232-dac9b622eaee.png)

**Comment by fannheyward** [comment] 2021-05-28 06:18
Sorry, I still can'r reproduce this.

1. `julia`
2. `]` to pkg, `generate helloworld`, exit

```
find .
.
./Project.toml
./src
./src/helloworld.jl
```

Put your Julia to helloworld.jl

<img width="475" alt="截屏2021-05-28 下午2 17 21" src="https://user-images.githubusercontent.com/345274/119938734-6d661f00-bfbf-11eb-873e-851d9b99d639.png">

**Comment by fannheyward** [comment] 2021-05-28 06:18
```
vim version: NVIM v0.5.0-dev+0a653f7ab
node version: v16.2.0
coc.nvim version: 0.0.80-7b4ac377d2
```

**Comment by fannheyward** [comment] 2021-05-28 06:20
@oblitum @lassepe sorry to ping you, but can you reproduce this?

**Comment by lassepe** [comment] 2021-05-28 06:53
I can also not reproduce this. In particular, I can also navigate the auto-completion list also with `ctr+p` as you seem to do (I usually use `<tab>`).
```
vim version: NVIM v0.4.4
node version: v16.1.0
coc.nvim version: 0.0.80-4cd2b40390
```

Maybe it is not a problem with LanguageServer.jl or the `coc-julia` plugin but rather with your vim-config, @JinraeKim? I can imagine that it is related to the fixes that were made to auto-completion recently here and in LanguageServer.jl. Maybe your old config worked with the old "broken" version of coc-julia because you found a quick-fix inside your vimrc that made it work. Now that the problem is fixed here at the root that quick-fix may break your workflow. (because the behavior of the plugin has changed). Maybe you can post your coc-related vimrc for further investigation.

Speculating on other things that may cause this:

- Maybe your coc-julia plugin still finds an old version of LanguageServer.jl. I don't know why that would happen but you could at least try uninstalling it from your global environment to make sure that you are not using an outdated version.
- Maybe you are using an old system-image? Try clearing `~/.config/coc/extensions/coc-julia-data/sysimg` before you recompile.

**Comment by JinraeKim** [comment] 2021-05-28 12:38
> * Maybe your coc-julia plugin still finds an old version of LanguageServer.jl. I don't know why that would happen but you could at least try uninstalling it from your global environment to make sure that you are not using an outdated version.

It seems that the base environment does not have manually installed `LanguageServer.jl`.
```julia➜  ~ julia -q -t 7
(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [fbb218c0] BSON v0.3.3
  [861a8166] Combinatorics v1.0.2
  [b0b7db55] ComponentArrays v0.9.10
  [a6e380b2] ControlSystems v0.9.2
  [f65535da] Convex v0.14.8
  [a93c6f00] DataFrames v1.1.1
  [864edb3b] DataStructures v0.18.9
  [31a5f54b] Debugger v0.6.7
  [0c46a032] DifferentialEquations v6.16.0
  [31c24e10] Distributions v0.24.18
  [587475ba] Flux v0.12.3
  [033835bb] JLD2 v0.4.5
  [6405355b] Mosek v1.1.3
  [1ec41992] MosekTools v0.9.4
  [102ac46a] MultivariatePolynomials v0.3.14
  [76087f3c] NLopt v0.6.2
  [e7bfaba1] NumericalIntegration v0.3.3
  [5fb14364] OhMyREPL v0.5.10
  [1dea7af3] OrdinaryDiffEq v5.53.2
  [d7d3b36b] ParameterSchedulers v0.2.2
  [b98c9c47] Pipe v1.3.0
  [14b8a8f1] PkgTemplates v0.7.16
  [91a5bcdd] Plots v1.14.0
  [295af30f] Revise v3.1.16
  [6038ab10] Rotations v1.0.2
  [5d786b92] TerminalLoggers v0.1.3
  [afbbf031] TypedPolynomials v0.2.9
  [37e2e46d] LinearAlgebra

```



> * Maybe you are using an old system-image? Try clearing `~/.config/coc/extensions/coc-julia-data/sysimg` before you recompile.
I removed all contents of the directory and tried to make a new sysimg using `:CocCommand julia.CompileLanguageServerSysimg`.
```
➜  ~ ls ~/.config/coc/extensions/coc-julia-data/sysimg
sysimg.dylib
```

```
/usr/local/bin/julia --project=/Users/jinrae/.config/coc/extensions/node_modules/coc-julia/server/compile_env /Users/jinrae/.config/coc/extensions/node_module
s/coc-julia/server/compile_env/compile.jl -s /Users/jinrae/.config/coc/extensions/node_modules/coc-julia/server/JuliaLS /Users/jinrae/.config/coc/extensions/c
oc-julia-data/sysimg
➜  ~ /usr/local/bin/julia --project=/Users/jinrae/.config/coc/extensions/node_modules/coc-julia/server/compile_env /Users/jinrae/.config/coc/extensions/node_m
odules/coc-julia/server/compile_env/compile.jl -s /Users/jinrae/.config/coc/extensions/node_modules/coc-julia/server/JuliaLS /Users/jinrae/.config/coc/extensi
ons/coc-julia-data/sysimg
[ Info: Building a sysimage for the environment '/Users/jinrae/.config/coc/extensions/node_modules/coc-julia/server/JuliaLS' to '/Users/jinrae/.config/coc/ext
ensions/coc-julia-data/sysimg'.
  0 dependencies successfully precompiled in 1 seconds (6 already precompiled)
  9 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages
[ Info: PackageCompiler: creating system image object file, this might take a while...
➜  ~
```

Error occurs again as
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43136096/119984766-bdafa200-bffc-11eb-8750-2e74e832c6fe.png">
In my case, the error is reproduced especially when the following is on the screen:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/43136096/119984819-d28c3580-bffc-11eb-9aad-4b1d9bbfc837.png">
Also, several trials may be required to see the error.

> Maybe you can post your coc-related vimrc for further investigation.

Please see the bottom of [my comment](https://github.com/fannheyward/coc-julia/issues/194#issuecomment-850161070).

**Comment by JinraeKim** [comment] 2021-05-28 14:19
I found that this phenomenon disappeared if I don't use [julia-vim](https://github.com/JuliaEditorSupport/julia-vim).

Is it possible to make a conflict with `julia-vim`?

**Comment by oblitum** [comment] 2021-05-28 14:24
@JinraeKim currently no, I  didn't yet look for an alternative. FWIW, if you find one please share ;-)

**Comment by JinraeKim** [comment] 2021-05-28 14:25
Sure :)
BTW, it's a really sad news to me 'cause I highly depend on the two plugins...

**Comment by oblitum** [comment] 2021-05-28 14:27
Given that the cause is found related to the two being used together, maybe others here can help further to make them work.

**Comment by oblitum** [comment] 2021-05-28 14:28
Also, make sure you have latest julia-vim.

**Comment by JinraeKim** [comment] 2021-05-28 14:30
> Also, make sure you have latest julia-vim.

I removed the previous `julia-vim` directory and reinstalled it via [vim-plug](https://github.com/junegunn/vim-plug).
So probably it is the latest one.

Is it?

**Comment by oblitum** [comment] 2021-05-28 14:34
Yep, that's enough for checking their latest stuff.

**Comment by fannheyward** [comment] 2021-05-28 14:40
> Note that the YouCompleteMe, neocomplcache, neocomplete and deoplete plug-ins do not work well with the suggestion of possible completions for partial matches

From Julia-vim README, looks like it's not working good with other completion plugins.

**Comment by fannheyward** [comment] 2021-05-28 14:44
I'm going to close this issue. Looks like julia-vim hijack your tab to do completion that conflict with coc.

**Closed** 2021-05-28 14:45 UTC
Labels: Can't reproduce

**Comment by lassepe** [comment] 2021-05-29 09:53
I agree that this issue should be closed because there is nothing that can be done about this in coc-julia it seems. That said, @JinraeKim for what it's worth: I am also using `julia-vim` and `coc-julia` and have no issues with the combination.

I too, noticed one important difference between your vimrc and mine:

You seem to have unicode completion enabled:

```
let g:latex_to_unicode_keymap = 1  " to avoid conflict with coc-julia and
```

try replacing it with this:

```
let g:latex_to_unicode_tab = 0
let g:latex_to_unicode_eager = 0
```

These settings disable the unicode completion of julia-vim. But the point is that you don't really need them because `coc-julia` already does the unicode completion for you.

**Comment by JinraeKim** [comment] 2021-05-30 05:45
> I agree that this issue should be closed because there is nothing that can be done about this in coc-julia it seems. That said, @JinraeKim for what it's worth: I am also using `julia-vim` and `coc-julia` and have no issues with the combination.
> 
> I noticed one important difference between your vimrc and mine. You seem to have unicode completion enabled for `julia-vim`.
> 
> ```
> let g:latex_to_unicode_keymap = 1  " to avoid conflict with coc-julia and
> ```
> 
> try replacing it with this:
> 
> ```
> let g:latex_to_unicode_tab = 0
> let g:latex_to_unicode_eager = 0
> ```
> 
> These settings disable the unicode completion of julia-vim. The point is that you don't really need them because `coc-julia` already does the unicode completion for you.

Unfortunately, this remedy also does not work for me.
