### ISSUE TITLE
manifest not compatible

### ISSUE THREAD

**Issue by beamiter** [fannheyward/coc-julia#306] opened 2022-04-06 13:16 UTC
yinj3@yinj3:~  projects  jl  traj$ /home/yinj3/.julia-1.6.5/bin/julia --project="/home/yinj3/.config/coc/extensions/node_modules/coc-julia/server/JuliaLS" --startup-file=no --history-file=no -e "using Pkg; Pkg.instantiate()"
ERROR: The manifest file you are using was most likely generated by a different version of Julia and is not compatible with this Julia version
Stacktrace:
 [1] load_urls(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
   @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:545
 [2] #download_source#57
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:733 [inlined]
 [3] download_source
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:732 [inlined]
 [4] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1408
 [5] instantiate
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1325 [inlined]
 [6] #instantiate#252
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321 [inlined]
 [7] instantiate()
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321
 [8] top-level scope
   @ none:1

**Comment by lassepe** [comment] 2022-04-06 20:17
The current Manifest is generated with Julia 1.7 and you are using Julia 1.6. One way to fix this is to download julia 1.7 and point the language server to it via the coc-config: `"julia.executablePath" : "/path/to/julia/1.7.2/bin/julia"`. This way, you can use whatever julia version you need for your project but still run the language server with julia 1.7.

Other than that, this is essentially a duplicate of #249.

**Comment by beamiter** [comment] 2022-04-07 01:48
Thanks a lot!

**Closed** 2022-10-04 06:41 UTC
